import Head from 'next/head'
import {Inter} from '@next/font/google'
import MainLayout from "@/layouts/MainLayout";
import {Provider} from "mobx-react";
import initializeStores from "@/stores/configuration/storeInitializer";
const stores: any = initializeStores();


const inter = Inter({subsets: ['latin']})

export default function Home() {
    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app"/>
                <meta name="viewport" content="width=device-width, initial-scale=1"/>
            </Head>
            <main>
                <Provider {...stores}>
                    <MainLayout/>
                </Provider>
            </main>
        </>
    )
}